### ISSUE TITLE
casadi for MATLAB 2013

### ISSUE THREAD

**Issue by avi22491** [casadi/optistack#1]
Hello, 

Does the present version 2.3.0 support on MATLAB R2013b?

**Comment by jaeandersson** [comment]
version 2.3.0 has only very experimental support for MATLAB. My recommendation would be to try out the develop branch or wait for the 2.4.0 release. Compiling from sources, I believe it should work with MATLAB R2013b. With the binaries, I'm not sure. @jgillis would have to answer.

**Comment by jaeandersson** [comment]
Forget my answer. I'll let @jgillis answer since this concerns optistack.

**Comment by jgillis** [comment]
The main page now offers a download for R2013a, which should work for R2013a too.
